# 1. Node 20 + Alpine 베이스 이미지
FROM node:20-alpine

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. 패키지 파일 복사 및 설치
COPY package*.json ./
RUN npm install

# 4. 전체 소스 복사
COPY . .

ARG NEXT_PUBLIC_FILE_SERVER_BASE_URL
ENV NEXT_PUBLIC_FILE_SERVER_BASE_URL=$NEXT_PUBLIC_FILE_SERVER_BASE_URL

# 5. 개발 서버 실행 (hot reload)
CMD ["npm", "run", "dev"]

# 6. Next.js 기본 포트
EXPOSE 3000